#define ERROR 1
#define KEYWORD 2
#define ID 3
#define COLN 4
#define OP 5 
#define SEMCOLN 6 
#define NUMBER 7
#define CHAR 8
#define LPR 9
#define RPR 10
#define LBRA 11
#define RBRA 12
#define COMP 13
#define ASSGN 14
#define COMA 15
#define WHITESPACE 16
#define LOGICAL 17
