#define ERROR 1
#define IF 2	
#define ELSE 3      
#define FOR 4      
#define SWITCH 5   
#define CASE 6   
#define WHILE 7     
#define RETURN 8   
#define UNTIL 9     
#define CONST 10    
#define ID 11
#define COLN 12
#define SEMCOLN 13 
#define FLOATING 14
#define CHARACTER 15
#define LPR 16
#define RPR 17
#define LBRA 18
#define RBRA 19
#define ASSGN 20
#define COMA 21
#define WHITESPACE 22 
#define PLUS 23     
#define MINUS 24     
#define DIV 25     
#define MULT 26     
#define MOD  27
#define GREATER 28
#define LESS 29
#define EQUALEQUAL 30
#define GREATEREQUAL 31
#define LESSEQUAL 32
#define NOTEQUAL 33
#define NOT 34
#define AND 35
#define XOR 36
#define OR  37
#define XNOR 38
#define SHIFTL 39
#define SHIFTR 40
#define PRINT  41
#define BREAK 42
#define CONTINUE 43
#define LABEL 44
#define GOTO 45
#define STRINGVAL 46
#define LSQUAREPR 47
#define RSQUAREPR 48        
#define DO 49;
#define DEFAULT 50;
#define INTEGER 51;
#define INT 52;
#define FLOAT 53;
#define CHAR 54;
#define VOID 55;
#define STRING 56;
#define INCREMENT 57;
#define DECREMENT 58;
#define BITOR 59;
#define BITXOR 60; 
#define BITXNOR 61;
#define BITAND 62;
#define BITNOT 63;
#define LINECOMMENT 64;
#define PRACOMMENT 65;